config/routes.rb
Rails.application.routes.draw do

  resources :motions
  get '/motions/:id/options', :to => 'motions#options'
  post '/motions/:id/options', :to => 'motions#add_new_option'
  delete '/motions/:id/options/', :to => 'motions#delete_option'
  get '/motions/:id/eligible', :to => 'motions#eligible'
  post '/motions/:id/save_eligible_teams', :to => 'motions#save_eligible_teams'
  get '/getdivisionchecklist', :to => 'motions#get_division_checklist'


  root 'static_pages#home'

  resources :admins
  resources :board_members
  resources :committees
  resources :divisions
  resources :games
  resources :hallof_famers
  resources :offers
  resources :profiles do
    get 'merge'
    get 'welcome_email'
    post 'merge', :action => 'run_merge'
  end

  # Roles and Permissions
  resources :profile_roles
  resources :roles_permissions
  resources :permissions
  resources :roles
  delete '/remove_permission_from_role', :to => 'roles_permissions#remove_permission_from_role'
  post '/add_permission_to_role', :to => 'roles_permissions#add_permission_to_role'
  post '/add_profile_to_role', :to => 'profile_roles#add_profile_to_role'
  delete '/remove_profile_from_role', :to => 'profile_roles#remove_profile_from_role'

  resources :rosters, :only => [:destroy]
  resources :teams
  resources :teamsnap_payments
  resources :teams_sponsors
  resources :sessions, only: [:new, :create, :destroy]
  resources :seasons
  resources :sessions, only: [:new, :create, :destroy]
  resources :sponsors

  resources :parks do
    resources :fields
  end

  resources :password_resets, only: [:new, :create, :edit, :update]
  post "/password_resets/new", to: 'password_resets#create'

  # games
  get '/games/:id/:teamid', to: 'games#game_attendance'
  post '/set_attendance', to: 'game_attendances#set_attendance'

  get '/home', to:'static_pages#home'
  get '/contact', to:'static_pages#contact'
  match '/feedback',  to: 'static_pages#feedback', via: 'get'

  # seasons
  get '/get_divisions_by_season', to:'seasons#get_divisions_by_season'
  get '/season/:seasonId/games', to:'seasons#games'
  get '/season/:id/nagaaa/ratings', to:'seasons#show_nagaaa_ratings'
  get '/season/:id/asana/ratings', to:'seasons#show_asana_ratings'

  # sessions
  match '/signup',  to: 'profiles#new', via: 'get'
  match '/signin',  to: 'sessions#new', via: 'get'
  get '/signout', to: 'sessions#destroy', via: 'delete'
  get '/teams_by_season', to: 'teams#get_teams_by_season'

  post '/add_player_to_roster', to: 'rosters#add_player_to_roster'

  get '/welcome', to: 'welcome#index'

  # sponsors
  get '/season_sponsors/:season_id', to: 'teams_sponsors#season_sponsors'

  #teamsnap api login
  get '/teamsnap/login', to: 'teamsnap#login'
  post '/teamsnap/login', to: 'teamsnap#teamsnaplogin'
  get '/teamsnap/logout', to: 'teamsnap#logout'
  get 'teamsnap/index', to:'teamsnap#index'
  get '/teamssnap/:teamId/:rosterId', to: 'teamsnap#team', as: 'rosterId'
  get '/ranking/:teamId/:rosterId/:playerId', to: 'teamsnap#ranking', as: 'playerId'
  get '/teamsnap', to:'teamsnap#redirect'
  get '/teamsnap/updateplayer', to:'payments_tracker#update_teamsnap_player'
  post '/teamsnap/divisions/import', to:'teamsnap#import_season_data'

  # teams
  get '/teams/:teamid/ratings', to:'teams#show_nagaaa_ratings'
  get '/teams/:teamid/ratings/asana', to:'teams#show_asana_ratings'
  post '/teams/asana/update', to:'teams#update_asana_rating'
  get '/teams/:teamid/ratings/import', to:'teams#import_asana_ratings'
  post '/teams/:teamid/ratings/runimport', to: 'teams#run_asana_import'

  # ratings
  resources :ratings
  resources :asana_ratings
  post '/ratings/update', to:'ratings#update_player'
  post '/ratings/new', to:'ratings#new_player'
  get '/rating/list/', to: 'ratings#list'
  get '/rating/duplicates', to:'ratings#show_duplicates'
  get '/rating/duplicates/remove', to:'ratings#remove_duplicates'
  get '/asana_ratings_by_division/:divisionId', to:'asana_ratings#index_by_division'



  # website iframes
  get '/showallsponsors', to: 'sponsors#all_sponsors'
  get '/sponsorscarousel', to: 'sponsors#sponsor_carousel'
  get '/showallhof', to: 'hallof_famers#all_hof'
  get '/showallboard', to: 'board_members#all_board'
  get '/showallcommittee', to: 'committees#all_committee'
  get '/showfields', to: 'parks#show_map'
  get '/showparks', to: 'parks#show_map'
  get '/loadsidebar', to: 'welcome#basl_sidebar'
  get '/loadcalendar', to: 'welcome#load_calendar'
  get '/getleaguesponsors', to: 'sponsors#league_sponsors'

  # parks
  post '/parks/set_all', to: 'parks#set_all'

  #admin panel
  get '/admin/home', to: 'admins#home'

  mount UserImpersonate::Engine => "/impersonate", as: "impersonate_engine"

  #payments trackers
  get 'payments', to:'payments_tracker#index'
  get 'payments/tracker', to:'payments_tracker#home'
  get 'payments/admin', to:'payments_tracker#admin'
  get 'payments/list', to: 'payments_tracker#list'
  get 'payments/list/add', to: 'payments_tracker#add_new_payment'
  get 'payments/sync', to: 'payments_tracker#sync'
  get 'payments/accounts/new', to: 'payments_tracker#new_account'
  post 'payments/accounts/create', to: 'payments_tracker#create_account'
  get 'payments/unassigned', to:'payments_tracker#unassigned'
  get 'payments/divisions', to: 'payments_tracker#divisions'
  get 'payments/division/:divisionId/', to: 'payments_tracker#division', as: 'divisionId'
  get 'payments/division/:divisionId/sendEmail', to: 'payments_tracker#emailDivisionRep'
  get 'payments/division/:divisionId/sendToWebteam', to: 'payments_tracker#emailWebteam'
  get 'payments/divisions/sendAll', to: 'payments_tracker#send_all_emails'

  # offers
  get 'alloffers', to: 'offers#all'

  # rosters
  get 'rosters/update_permissions', to: 'rosters#update_permissions'

  # divisions
  get 'teamsnap/divisions/import', to: 'teamsnap#import_divisions'
  get '/divisions/:id/ratings', to:'divisions#show_nagaaa_ratings'
  get '/divisions/asana/:id/ratings', to:'divisions#show_asana_ratings'

  # profiles
  get 'pickup', to: 'profiles#pickup_players'
  get 'pickup/export', to:'profiles#export_pickup'
  post 'pickup/export_players', to: 'profiles#export_players'
  get 'profile_details', to: 'profiles#details'

  get "/404", :to => "errors#error_404"
  get "/422", :to => "errors#error_404"
  get "/500", :to => "errors#error_500"
  get '/403', to: 'errors#error_403'

  # schedule
  match '/schedule',  to: 'schedules#index', via: 'get'
  get '/schedule/:divisionId', :to => 'schedules#generate'
  get '/scheduler/run', :to => 'schedules#run_generator'
  get '/import', :to => 'imports#index'
  post '/import/upload', :to => 'imports#upload'

  # ratings
  get "/asana_rating_to_profile/:profile_id", :to => 'asana_ratings#new_for_profile'
  get "/nagaaa_rating_to_profile/:profile_id", :to => 'ratings#new_for_profile'

end

app/models/hallof_famer.rb
class HallofFamer < ActiveRecord::Base
  belongs_to :profile
end

app/controllers/hallof_famers_controller.rb
class HallofFamersController < ApplicationController
  before_action :set_hallof_famer, only: [:show, :edit, :update, :destroy]
  before_filter :only_for_admin, only: [:edit, :update, :destroy]

  # GET /hallof_famers
  # GET /hallof_famers.json
  def index
    @hallof_famers = HallofFamer.order('display_order ASC').all
  end

  # GET /hallof_famers/1
  # GET /hallof_famers/1.json
  def show
  end

  # GET /hallof_famers/new
  def new
    @hallof_famer = HallofFamer.new
    @profiles = Profile.all
  end

  # GET /hallof_famers/1/edit
  def edit
    @profiles = Profile.all
  end

  # POST /hallof_famers
  # POST /hallof_famers.json
  def create
    @hallof_famer = HallofFamer.new(hallof_famer_params)

    respond_to do |format|
      if @hallof_famer.save
        format.html { redirect_to @hallof_famer, notice: 'Hallof famer was successfully created.' }
        format.json { render :show, status: :created, location: @hallof_famer }
      else
        format.html { render :new }
        format.json { render json: @hallof_famer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hallof_famers/1
  # PATCH/PUT /hallof_famers/1.json
  def update
    respond_to do |format|
      if @hallof_famer.update(hallof_famer_params)
        format.html { redirect_to @hallof_famer, notice: 'Hallof famer was successfully updated.' }
        format.json { render :show, status: :ok, location: @hallof_famer }
      else
        format.html { render :edit }
        format.json { render json: @hallof_famer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hallof_famers/1
  # DELETE /hallof_famers/1.json
  def destroy
    @hallof_famer.destroy
    respond_to do |format|
      format.html { redirect_to hallof_famers_url, notice: 'Hallof famer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def all_hof
    @hallof_famers = HallofFamer.order('display_order ASC').where(:is_active => true)
    render layout: false
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hallof_famer
      @hallof_famer = HallofFamer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hallof_famer_params
      params.require(:hallof_famer).permit(:profile_id, :date_inducted, :is_active, :is_inducted, :details, :profile_id, :image_url, :display_order)
    end
end

app/helpers/hallof_famers_helper.rb
module HallofFamersHelper
end

app/views/hallof_famers/_form.html.haml
= form_for @hallof_famer,:html => {:class => 'form-horizontal'} do |f|
  - if @hallof_famer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@hallof_famer.errors.count, "error")} prohibited this hallof_famer from being saved:"
      %ul
        - @hallof_famer.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :display_order, {:class => 'col-sm-2 control-label'}
    .col-sm-10
      = f.number_field :display_order, {:class => 'form-control'}
  .form-group
    = f.label :profile_id, {:class => 'col-sm-2 control-label'}
    .col-sm-10
      = render partial: "shared/profile_picker", locals: { profiles: @profiles, currentValue: @hallof_famer.profile_id,
        placeHolder: "Choose a User Profile",selectName: 'hallof_famer[profile_id]',
        selectId: 'hallof_famer_profile_id'}
  .form-group
    = f.label :date_inducted, {:class => 'col-sm-2 control-label'}
    .col-sm-10
      = f.datetime_select :date_inducted, {:class => 'form-control'}
  .form-group
    = f.label :details, {:class => 'col-sm-2 control-label'}
    .col-sm-10
      =f.text_area :details, {:class => 'form-control'}
  .form-group
    = f.label :image_url, {:class => 'col-sm-2 control-label'}
    .col-sm-10
      =f.text_field :image_url, {:class => 'form-control'}
  .form-group
    .col-sm-offset-2.col-sm-10
      .checkbox
        %label
          = f.check_box :is_active
          Is Active Hall of Famer?
  .form-group
    .col-sm-offset-2.col-sm-10
      .checkbox
        %label
          = f.check_box :is_inducted
          Is Inducted?
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit 'Save', {:class => 'btn btn-primary'}

app/views/hallof_famers/_hof_card.haml
%li.hof-card{:ontouchstart=>"this.classList.toggle('hover');"}
  .hof-card-front
    .hof-card-image
      %img{:src=>"#{hof.image_url ? hof.image_url : 'https://style.anu.edu.au/_anu/4/images/placeholders/person_6x8.png'}"}
      .hof-card-overlay
    .hof-card-name
      - if hof.profile
        = hof.profile.name
  .hof-card-back
    .hof-card-back-container
      .hof-card-header
        .hof-card-name
          - if hof.profile
            =hof.profile.name
        .hof-card-inducted
          Inducted in
          =hof.date_inducted.strftime("%Y")
      .hof-card-player-details
        %p=hof.details

app/views/hallof_famers/all_hof.html.haml
%html
  %head
    %link{:href => "https://fonts.googleapis.com/css?family=Montserrat", :rel => "stylesheet", :type => "text/css"}/
    =stylesheet_link_tag "hofsList.css"
  %body
    %ul.js-hof-list.hof-list
      - @hallof_famers.each do |hof|
        =render partial: 'hallof_famers/hof_card', locals: { hof: hof }
        
    = javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"

app/views/hallof_famers/edit.html.haml
- content_for :panel_head do
  %h1= "Editing Hall of Fame Plaque for #{@hallof_famer.first_name} #{@hallof_famer.last_name}"
  = render partial: "shared/actions/edit_actions", locals: { allPath: hallof_famers_path, fieldName: 'HOF', showPath: @hallof_famer}

= render 'form'

app/views/hallof_famers/index.html.haml
- content_for :panel_head do
  %h1 Current Hall of Famers
  = render partial: "shared/actions/view_all_actions", locals: { newPath: new_hallof_famer_path}

%table.table.table-striped.table-bordered.table-condensed
  %tr
    %th Profile
    %th Order
    %th
    %th Name
    %th Year Inducted
    %th Details
    %th Active?
    %th Inducted?
    %th.actions-column

  - @hallof_famers.each do |hallof_famer|
    %tr
      %th
        -if hallof_famer.profile
          =hallof_famer.profile.id
      %th=hallof_famer.display_order
      %th
        -if hallof_famer.image_url
          .image30-wrapper
            %img{:src => hallof_famer.image_url}
      %td{:class => hallof_famer.profile ? '' : 'danger danger-column'}
        -if hallof_famer.profile
          =hallof_famer.profile.id= link_to "#{hallof_famer.profile.name}", hallof_famer
        - else
          = render partial: "shared/warning_column", locals: { text: 'No Profile'}

      %td= hallof_famer.date_inducted.strftime("%Y")
      %td
        %p= hallof_famer.details
      %td=yes_or_no_icon(hallof_famer.is_active).html_safe
      %td=yes_or_no_icon(hallof_famer.is_inducted).html_safe
      %td= render partial: "shared/actions/table_actions", locals: { editPath: edit_hallof_famer_path(hallof_famer), deletePath: hallof_famer}

app/views/hallof_famers/new.html.haml
- content_for :panel_head do
  %h1 Create New Hall of Famer
  = render partial: "shared/actions/all", locals: { allPath: hallof_famers_path}

= render 'form'

app/views/hallof_famers/show.html.haml
- content_for :panel_head do
  %h1
    =@hallof_famer.first_name
    =@hallof_famer.last_name
  = render partial: "shared/actions/show_actions", locals: { editPath: edit_hallof_famer_path(@hallof_famer), fieldName: 'Field', allPath: hallof_famers_path}
%ul.js-hof-list.hof-list
  =render partial: 'hallof_famers/hof_card', locals: { hof: @hallof_famer }
%p
  %b Display Order:
  = @hallof_famer.display_order
%p
  %b Profile:
  = @hallof_famer.profile_id
%p
  %b Year inducted:
  = @hallof_famer.date_inducted.strftime("%Y")
%p
  %b Player Details:
  = @hallof_famer.details
%p
  %b Is active:
  = @hallof_famer.is_active
%p
  %b Is inducted:
  = @hallof_famer.is_inducted