config/routes.rb
Rails.application.routes.draw do

  resources :motions
  get '/motions/:id/options', :to => 'motions#options'
  post '/motions/:id/options', :to => 'motions#add_new_option'
  delete '/motions/:id/options/', :to => 'motions#delete_option'
  get '/motions/:id/eligible', :to => 'motions#eligible'
  post '/motions/:id/save_eligible_teams', :to => 'motions#save_eligible_teams'
  get '/getdivisionchecklist', :to => 'motions#get_division_checklist'


  root 'static_pages#home'

  resources :admins
  resources :board_members
  resources :committees
  resources :divisions
  resources :games
  resources :hallof_famers
  resources :offers
  resources :profiles do
    get 'merge'
    get 'welcome_email'
    post 'merge', :action => 'run_merge'
  end

  # Roles and Permissions
  resources :profile_roles
  resources :roles_permissions
  resources :permissions
  resources :roles
  delete '/remove_permission_from_role', :to => 'roles_permissions#remove_permission_from_role'
  post '/add_permission_to_role', :to => 'roles_permissions#add_permission_to_role'
  post '/add_profile_to_role', :to => 'profile_roles#add_profile_to_role'
  delete '/remove_profile_from_role', :to => 'profile_roles#remove_profile_from_role'

  resources :rosters, :only => [:destroy]
  resources :teams
  resources :teamsnap_payments
  resources :teams_sponsors
  resources :sessions, only: [:new, :create, :destroy]
  resources :seasons
  resources :sessions, only: [:new, :create, :destroy]
  resources :sponsors

  resources :parks do
    resources :fields
  end

  resources :password_resets, only: [:new, :create, :edit, :update]
  post "/password_resets/new", to: 'password_resets#create'

  # games
  get '/games/:id/:teamid', to: 'games#game_attendance'
  post '/set_attendance', to: 'game_attendances#set_attendance'

  get '/home', to:'static_pages#home'
  get '/contact', to:'static_pages#contact'
  match '/feedback',  to: 'static_pages#feedback', via: 'get'

  # seasons
  get '/get_divisions_by_season', to:'seasons#get_divisions_by_season'
  get '/season/:seasonId/games', to:'seasons#games'
  get '/season/:id/nagaaa/ratings', to:'seasons#show_nagaaa_ratings'
  get '/season/:id/asana/ratings', to:'seasons#show_asana_ratings'

  # sessions
  match '/signup',  to: 'profiles#new', via: 'get'
  match '/signin',  to: 'sessions#new', via: 'get'
  get '/signout', to: 'sessions#destroy', via: 'delete'
  get '/teams_by_season', to: 'teams#get_teams_by_season'

  post '/add_player_to_roster', to: 'rosters#add_player_to_roster'

  get '/welcome', to: 'welcome#index'

  # sponsors
  get '/season_sponsors/:season_id', to: 'teams_sponsors#season_sponsors'

  #teamsnap api login
  get '/teamsnap/login', to: 'teamsnap#login'
  post '/teamsnap/login', to: 'teamsnap#teamsnaplogin'
  get '/teamsnap/logout', to: 'teamsnap#logout'
  get 'teamsnap/index', to:'teamsnap#index'
  get '/teamssnap/:teamId/:rosterId', to: 'teamsnap#team', as: 'rosterId'
  get '/ranking/:teamId/:rosterId/:playerId', to: 'teamsnap#ranking', as: 'playerId'
  get '/teamsnap', to:'teamsnap#redirect'
  get '/teamsnap/updateplayer', to:'payments_tracker#update_teamsnap_player'
  post '/teamsnap/divisions/import', to:'teamsnap#import_season_data'

  # teams
  get '/teams/:teamid/ratings', to:'teams#show_nagaaa_ratings'
  get '/teams/:teamid/ratings/asana', to:'teams#show_asana_ratings'
  post '/teams/asana/update', to:'teams#update_asana_rating'
  get '/teams/:teamid/ratings/import', to:'teams#import_asana_ratings'
  post '/teams/:teamid/ratings/runimport', to: 'teams#run_asana_import'

  # ratings
  resources :ratings
  resources :asana_ratings
  post '/ratings/update', to:'ratings#update_player'
  post '/ratings/new', to:'ratings#new_player'
  get '/rating/list/', to: 'ratings#list'
  get '/rating/duplicates', to:'ratings#show_duplicates'
  get '/rating/duplicates/remove', to:'ratings#remove_duplicates'
  get '/asana_ratings_by_division/:divisionId', to:'asana_ratings#index_by_division'



  # website iframes
  get '/showallsponsors', to: 'sponsors#all_sponsors'
  get '/sponsorscarousel', to: 'sponsors#sponsor_carousel'
  get '/showallhof', to: 'hallof_famers#all_hof'
  get '/showallboard', to: 'board_members#all_board'
  get '/showallcommittee', to: 'committees#all_committee'
  get '/showfields', to: 'parks#show_map'
  get '/showparks', to: 'parks#show_map'
  get '/loadsidebar', to: 'welcome#basl_sidebar'
  get '/loadcalendar', to: 'welcome#load_calendar'
  get '/getleaguesponsors', to: 'sponsors#league_sponsors'

  # parks
  post '/parks/set_all', to: 'parks#set_all'

  #admin panel
  get '/admin/home', to: 'admins#home'

  mount UserImpersonate::Engine => "/impersonate", as: "impersonate_engine"

  #payments trackers
  get 'payments', to:'payments_tracker#index'
  get 'payments/tracker', to:'payments_tracker#home'
  get 'payments/admin', to:'payments_tracker#admin'
  get 'payments/list', to: 'payments_tracker#list'
  get 'payments/list/add', to: 'payments_tracker#add_new_payment'
  get 'payments/sync', to: 'payments_tracker#sync'
  get 'payments/accounts/new', to: 'payments_tracker#new_account'
  post 'payments/accounts/create', to: 'payments_tracker#create_account'
  get 'payments/unassigned', to:'payments_tracker#unassigned'
  get 'payments/divisions', to: 'payments_tracker#divisions'
  get 'payments/division/:divisionId/', to: 'payments_tracker#division', as: 'divisionId'
  get 'payments/division/:divisionId/sendEmail', to: 'payments_tracker#emailDivisionRep'
  get 'payments/division/:divisionId/sendToWebteam', to: 'payments_tracker#emailWebteam'
  get 'payments/divisions/sendAll', to: 'payments_tracker#send_all_emails'

  # offers
  get 'alloffers', to: 'offers#all'

  # rosters
  get 'rosters/update_permissions', to: 'rosters#update_permissions'

  # divisions
  get 'teamsnap/divisions/import', to: 'teamsnap#import_divisions'
  get '/divisions/:id/ratings', to:'divisions#show_nagaaa_ratings'
  get '/divisions/asana/:id/ratings', to:'divisions#show_asana_ratings'

  # profiles
  get 'pickup', to: 'profiles#pickup_players'
  get 'pickup/export', to:'profiles#export_pickup'
  post 'pickup/export_players', to: 'profiles#export_players'
  get 'profile_details', to: 'profiles#details'

  get "/404", :to => "errors#error_404"
  get "/422", :to => "errors#error_404"
  get "/500", :to => "errors#error_500"
  get '/403', to: 'errors#error_403'

  # schedule
  match '/schedule',  to: 'schedules#index', via: 'get'
  get '/schedule/:divisionId', :to => 'schedules#generate'
  get '/scheduler/run', :to => 'schedules#run_generator'
  get '/import', :to => 'imports#index'
  post '/import/upload', :to => 'imports#upload'

  # ratings
  get "/asana_rating_to_profile/:profile_id", :to => 'asana_ratings#new_for_profile'
  get "/nagaaa_rating_to_profile/:profile_id", :to => 'ratings#new_for_profile'

end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :profile
  validate :ratings_cannot_be_out_of_order
  validates :profile_id, presence: true


  def to_s
    ratingstring = "#{section_to_s(throwing_ratings)},#{section_to_s(fielding_ratings)},#{section_to_s(running_ratings)},#{section_to_s(hitting_ratings)}"
    
  end

  def section_to_s(ratings)
    ratingstring = nil
    ratings.each do |rating|
      if ratingstring.nil?
        ratingstring ="#{rating}"
      else
        ratingstring ="#{ratingstring},#{rating}"
      end
    end
    ratingstring
  end
  #
  # Validating fielding, can't rank levels out of order
  # 
  def ratings_cannot_be_out_of_order
    check_ratings(throwing_ratings, 'throwing')
    check_ratings(fielding_ratings, 'fielding')
    check_ratings(running_ratings, 'running')
    check_ratings(hitting_ratings, 'hitting')
  end

  #
  # Reverse loops through the ratings to make sure we 
  # don't have ratings levels that are ranked out of order
  # i.e. can't be level 1 and a level 3 but NOT a level 2
  #
  def check_ratings(ratings, type)
    current_value = 0

    ratings.reverse_each do |rating|
      if (rating.present? && rating < current_value)
        errors.add(:rating, "Cannot rate #{type} levels out of order")
      else
        current_value = rating
      end
    end

  end

  # calculating the total throwing rating
  def throwing_total
    self.rating_1 +
    self.rating_2 +
    self.rating_3 +
    self.rating_4 +
    self.rating_5
  end

  # calculating the total fielding rating
  def fielding_total
    self.rating_6 +
    self.rating_7 +
    self.rating_8 +
    self.rating_9 +
    self.rating_10 +
    self.rating_11 +
    self.rating_12 +
    self.rating_13 +
    self.rating_14
  end

  # calulate the baserunning total
  def baserunning_total
    self.rating_15 + 
    self.rating_16 +
    self.rating_17 +
    self.rating_18
  end

  # calculating the hitting total
  def hitting_total
    self.rating_19 +
    self.rating_20 +
    self.rating_21 +
    self.rating_22 +
    self.rating_23 +
    self.rating_24 +
    self.rating_25 +
    self.rating_26 +
    self.rating_27
  end

  # total rating
  def total
    throwing_total +
    fielding_total +
    baserunning_total +
    hitting_total
  end

  def throwing_ratings
    throwing = Array.new
    throwing.push(self.rating_1)
    throwing.push(self.rating_2)
    throwing.push(self.rating_3)
    throwing.push(self.rating_4)
    throwing.push(self.rating_5)
  end

  def fielding_ratings
    fielding = Array.new
    fielding.push(self.rating_6)
    fielding.push(self.rating_7)
    fielding.push(self.rating_8)
    fielding.push(self.rating_9)
    fielding.push(self.rating_10)
    fielding.push(self.rating_11)
    fielding.push(self.rating_12)
    fielding.push(self.rating_13)
    fielding.push(self.rating_14)
  end

  def running_ratings
    running = Array.new
    running.push(self.rating_15)
    running.push(self.rating_16)
    running.push(self.rating_17)
    running.push(self.rating_18)
  end

  def hitting_ratings
    hitting = Array.new
    hitting.push(self.rating_19)
    hitting.push(self.rating_20)
    hitting.push(self.rating_21)
    hitting.push(self.rating_22)
    hitting.push(self.rating_23)
    hitting.push(self.rating_24)
    hitting.push(self.rating_25)
    hitting.push(self.rating_26)
    hitting.push(self.rating_27)
  end
end

app/helpers/ratings_helper.rb
module RatingsHelper

  # connected questions
  # yes to 2 = yes to 1
  # yes to 3 = yes to 1, 2
  # yes to 4 = yes to 1, 2, 3
  # 
  # 6-14
  # 15 - 17
  # 19-21
  # 23 - 25
  def ratings_question(num, question)
    label_for("#{num}. #{question}")
  end

  def set_question(question)
    question_string = 'Does the player have the ability to... <br/>'
    if (question.size > 1)
      question.each_with_index do |q, index|
        question_string += "#{q}"
        if index != question.size - 1
          question_string += '<br><span class="text-center">OR</span><br>'
        end
      end
    else
      question_string += question.first
    end
    question_string.html_safe
  end

  def question_1
    ["occasionally throw a ball through the air 65 feet or better in the vicinity of another player? (65 feet is the distance between bases)"]
  end

  def question_2
    ['consistently throw a ball through the air 90 feet or better in the vicinity of another player?
    (90 feet is the distance between 3rd and 1st)',
      
    'occasionally throw to the proper place turning accurate infield plays against runners with average base running speed?']
  end

  def question_3
    ['occasionally throw a ball through the air 90 feet or better without a rainbow arc in the vicinity of another player?', 
      'consistently throw to the proper place turning accurate infield plays against runner with average base running speed?'] 
  end

  def question_4
    ['consistently throw a ball through the air 90 feet or better without a rainbow arc in the vicinity of another player?']
  end

  def question_5
    ['consistently throw without a rainbow arc to the proper place turning accurate infield plays against aggressive runners with above average speed?',
    'consistently make long throws without a rainbow arc from the outfield directly and accurately to the proper base completing proper plays against aggressive runners with above average speed?']
  end

  def question_6
    ['occasionally on purpose catch balls that are thrown to the player with a rainbow arc?']
  end

  def question_7
    ['occasionally on purpose catch balls that are thrown to the player without a rainbow arc?']
  end

  def question_8
    ['consistently on purpose field slow hit balls that are within a few steps?',

      'consistently on purpose catch fly balls that are within 15 feet? ']
  end

  def question_9
    ['consistently on purpose field medium hit balls that are within a few steps?',
      'consistently on purpose catch fly balls that are more than 15 feet away? ']
  end

  def question_10
    ['occasionally on purpose field medium hit balls that are in the hole?',
      'occasionally on purpose catch fly balls that are more than 30 feet away? ']
  end

  def question_11
    ['consistently on purpose field medium hit balls that are in the hole?',
      'consistently on purpose catch fly balls that are more than 30 feet away?'
    ]
  end

  def question_12
    ['occasionally on purpose field hard hit balls that are in the hole?',
      'occasionally on purpose stop line drives in the gaps from getting by the outfielders? '
    ]
  end

  def question_13
    ['consistently on purpose field hard hit balls that are in the hole?',
      'consistently on purpose stop line drives in the gaps from getting by the outfielders?']
  end

  def question_14
    ['occasionally on purpose make spectacular catches? ']
  end

  def question_15
    ['go from base to base utilizing rudimentary knowledge of the rules?']
  end

  def question_16
    ['run with average speed and occasionally take extra bases on good hits or errors against a limited level of defense? ']
  end

  def question_17
    ['run aggressively with average or better speed and occasionally take extra bases on good hits',
      'errors against an intermediate level of defense?']
  end

  def question_18
    ['run very aggressively and occasionally take extra bases on good hits or errors against an
 exceptional level of defense?']
  end

  def question_19
    ['occasionally hit a fair ball?']
  end

  def question_20
    ['consistently hit a fair ball?']
  end

  def question_21
    ['occasionally hit a fair ball with at least medium velocity?']
  end

  def question_22
    ['consistently hit a fair ball with at least medium velocity? ']
  end

  def question_23
    ['consistently reach base safely on a batted ball against a limited level of defense?',
     'occasionally reach base safely on a batted ball against an intermediate level of defense?']    
  end

  def question_24
    ['consistently reach base safely on a batted ball against an intermediate level of
defense?',
      'occasionally reach base safely on a batted ball against an exceptional level of defense?']
  end

  def question_25
    ['consistently reach base safely on a batted ball with high velocity against an intermediate level of defense', 
      'consistently reach base safely on a batted ball against an exceptional level of defense?']
  end

  def question_26
    ['consistently reach base safely on a batted ball with high velocity against an exceptional level of defense?']
  end

  def question_27
    ['occasionally hit a ball over a 300’ fence?']
  end

  def q_response(value)
    if value == 1 
      '1 - Yes'
    else
      '0 - No'
    end
  end

  def ratings_options
    [
      ['0 - No', 0], 
      ['1 - Yes', 1]
    ]
  end


  # sortable Columns for view
  def sort_column
    params[:sort].present? ? params[:sort] : "profiles.last_name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/views/ratings/_form.haml
= form_for @rating,:html => {:class => 'form-horizontal'} do |f|
  - if @rating.errors.any?
    #error_explanation
      %h2= "#{pluralize(@rating.errors.count, "error")} prohibited this NAGAAA rating from being saved:"
      %ul
        - @rating.errors.full_messages.each do |msg|
          %li= msg
  - if @rating.profile.present?
    =f.hidden_field :profile_id
  - else
    .field
      = f.label :profile_id
      = f.number_field :profile_id
  -#.field
    = f.label :is_approved
    = f.check_box :is_approved
  -#.field
    = f.label :approved_profile_id
    = f.number_field :approved_profile_id
  = render layout: 'shared/rating_group', locals: {rating_title: 'Throwing', rating_class: 'throwing'} do
    = render partial:'shared/ratings/question_group', locals: {questions: @questions[:throwing], f: f}

  = render layout: 'shared/rating_group', locals: {rating_title: 'Fielding', rating_class: 'fielding'} do
    = render partial:'shared/ratings/question_group', locals: {questions: @questions[:fielding], f: f}

  = render layout: 'shared/rating_group', locals: {rating_title: 'Baserunning', rating_class: 'running'} do
    = render partial:'shared/ratings/question_group', locals: {questions: @questions[:running], f: f}

  = render layout: 'shared/rating_group', locals: {rating_title: 'Hitting', rating_class: 'hitting'} do
    = render partial:'shared/ratings/question_group', locals: {questions: @questions[:hitting], f: f}
      
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit 'Save', {:class => 'btn btn-primary'}

app/views/ratings/_ratings.haml
%table.table.table-striped.table-bordered.table-condensed.ratings-display-table
  %tr
    %th
    %th
    %th
    %th
    %th
    %th
    %th
    %th
    %th
    %th.center-column.throwing{:colspan => 5, :align => 'center', :bgcolor => '#f0f'} Throwing
    %th.center-column.fielding{:colspan => 9, :align => 'center'} Fielding
    %th.center-column.baserunning{:colspan => 4, :align => 'center'} Baserunning
    %th.center-column.hitting{:colspan => 9, :align => 'center'} Hitting
  %tr
    %th First Name
    %th Last Name
    %th E-mail
    %th DOB
    %th 
    %th Division
    %th Team
    %th
    %th Rating
    %th.throwing 1
    %th.throwing 2
    %th.throwing 3
    %th.throwing 4
    %th.throwing 5
    %th.fielding 6
    %th.fielding 7
    %th.fielding 8
    %th.fielding 9
    %th.fielding 10
    %th.fielding 11
    %th.fielding 12
    %th.fielding 13
    %th.fielding 14
    %th.baserunning 15
    %th.baserunning 16
    %th.baserunning 17
    %th.baserunning 18
    %th.hitting 19
    %th.hitting 20
    %th.hitting 21
    %th.hitting 22
    %th.hitting 23
    %th.hitting 24
    %th.hitting 25
    %th.hitting 26
    %th.hitting 27

  - season.divisions.each do |division|
    - division.teams.each do |team|
      - team.rosters.each do |player|
        %tr
          %td=player.profile.first_name
          %td=player.profile.last_name
          %td=player.profile.email
          %td=player.profile.dob
          %td=#intentionally left blank
          %td=division.description
          %td=team.name
          %td

          - rating = player.profile.get_rating
          -if rating
            %td.center-column=rating.total
            %td.throwing=rating.rating_1
            %td.throwing=rating.rating_2
            %td.throwing=rating.rating_3
            %td.throwing=rating.rating_4
            %td.throwing=rating.rating_5
            %td.fielding=rating.rating_6
            %td.fielding=rating.rating_7
            %td.fielding=rating.rating_8
            %td.fielding=rating.rating_9
            %td.fielding=rating.rating_10
            %td.fielding=rating.rating_11
            %td.fielding=rating.rating_12
            %td.fielding=rating.rating_13
            %td.fielding=rating.rating_14
            %td.baserunning=rating.rating_15
            %td.baserunning=rating.rating_16
            %td.baserunning=rating.rating_17
            %td.baserunning=rating.rating_18
            %td.hitting=rating.rating_19
            %td.hitting=rating.rating_20
            %td.hitting=rating.rating_21
            %td.hitting=rating.rating_22
            %td.hitting=rating.rating_23
            %td.hitting=rating.rating_24
            %td.hitting=rating.rating_25
            %td.hitting=rating.rating_26
            %td.hitting=rating.rating_27
          - else
            %td{:colspan => 28} No Player Rating

app/views/ratings/edit.html.haml
- content_for :panel_head do
  %h1 
    Editing Rating for
    =@rating.profile.name
  = render partial: "shared/actions/edit_actions", locals: { allPath: ratings_path, fieldName: 'NAGAAA Rating', showPath: @rating}

= render 'form'

app/views/ratings/index.csv.haml
,,,,,,,,,Throwing,,,,,Fielding,,,,,,,,Baserunning,,,,,Hitting,,,,,,,,,
First Name,Last Name,E-Mail,DOB,,Division,Team,,Rating,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27
-@active_season.divisions.each do |division|
  - division.teams.each do |team|
    - team.rosters.each do |player| 
      = "#{player.profile.first_name},#{player.profile.last_name},#{player.profile.email},#{player.profile.dob},,#{division.description},#{team.name},,#{player.profile.rating ? player.profile.rating.total : 'No Player Rating' },#{player.profile.rating ? player.profile.rating.to_s : ''}"

app/views/ratings/index.html.haml
- content_for :panel_head do
  %h1 
    Big Apple Softball League Player Ratings for
    =@active_season.description 
  = link_to raw('<i class="fa fa-download"></i> Download CSV'), ratings_path('csv'), :class => 'btn btn-default'
  = link_to 'Show Duplicate Ratings', '/rating/duplicates', :class=> 'btn btn-default'

Showing Ratings

app/views/ratings/remove_duplicates.html.haml
- content_for :panel_head do
  %h1 
    Remove Duplicate Ratings

.well
  Duplicate Ratings Destroyed!

app/views/ratings/show.html.haml
- content_for :panel_head do
  %h1 
    Show Rating
    =@rating.profile.name
  = render partial: "shared/actions/show_actions", locals: { editPath: edit_rating_path(@rating), fieldName: 'Rating', allPath: ratings_path}
  = link_to "View #{@rating.profile.name}", @rating.profile

.panel.panel-default
  .panel-body
    %p  As a member of NAGAAA it is our duty and responsibility to rate all our league players and report these ratings, when applicable, to NAGAAA. The purpose of the ratings is to ensure all players are eligible to play in the appropriate NAGAAA division (A, B, C or D) should they attend a NAGAAA World Series or any other sanctioned NAGAAA slow-pitch, softball tournament. The ratings are not intended to forcibly move players into a higher division. Proper ratings protect players and teams - from penalty or expulsion from NAGAAA sanctioned tournaments – by fairly placing them into the division of their true caliber where they may compete against their peers.

    %h4 Definitions for All Questions
    %ul.list-group
      %li.list-group-item
        %strong OCCASIONALLY
        to be able to perform the particular skill without regularity.
        This means the skill can be performed 2 out of 5 times
      %li.list-group-item
        %strong CONSISTENTLY
        to be able to perform the particular skill with regularity or more often than not.
        This mean the skill can be performed 4 out of 5 times
      %li.list-group-item
        Consider the field conditions and weather to be normal when answering these questions. You are not factoring
        bad field or weather conditions.

    %ul.list-group
      %li.list-group-item
        %p 
          Choose a 
          %b YES 
          or 
          %b NO 
          answer for each question.
      %li.list-group-item
        %p 
          Many questions have multiple parts. A YES to any one part is a yes to the entire question.

= render layout: 'shared/rating_group', locals: {rating_title: 'Throwing', rating_class: 'throwing'} do
  %ul.list-group
    %li.list-group-item
      %h5=set_question(question_1)
      %p=q_response(@rating.rating_1)
    %li.list-group-item
      %h5=set_question(question_2)
      %p=q_response(@rating.rating_2)
    %li.list-group-item
      %h5=set_question(question_3)
      %p=q_response(@rating.rating_3)
    %li.list-group-item
      %h5=set_question(question_4)
      %b=q_response(@rating.rating_4)
    %li.list-group-item
      %h5=set_question(question_5)
      %b=q_response(@rating.rating_5)

= render layout: 'shared/rating_group', locals: {rating_title: 'Fielding', rating_class: 'fielding'} do
  %ul.list-group
    %li.list-group-item
      %h5=set_question(question_6)
      %b=q_response(@rating.rating_6)
    %li.list-group-item
      %h5=set_question(question_7)
      %b=q_response(@rating.rating_7)
    %li.list-group-item
      %h5=set_question(question_8)
      %b=q_response(@rating.rating_8)
    %li.list-group-item
      %h5=set_question(question_9)
      %b=q_response(@rating.rating_9)
    %li.list-group-item
      %h5=set_question(question_10)
      %b=q_response(@rating.rating_10)
    %li.list-group-item
      %h5=set_question(question_11)
      %b=q_response(@rating.rating_11)
    %li.list-group-item
      %h5=set_question(question_12)
      %b=q_response(@rating.rating_12)
    %li.list-group-item
      %h5=set_question(question_13)
      %b=q_response(@rating.rating_13)
    %li.list-group-item
      %h5=set_question(question_14)
      %b=q_response(@rating.rating_14)

= render layout: 'shared/rating_group', locals: {rating_title: 'Baserunning', rating_class: 'running'} do
  %ul.list-group
    %li.list-group-item
      %h5=set_question(question_15)
      %b=q_response(@rating.rating_15)
    %li.list-group-item
      %h5=set_question(question_16)
      %b=q_response(@rating.rating_16)
    %li.list-group-item
      %h5=set_question(question_17)
      %b=q_response(@rating.rating_17)
    %li.list-group-item
      %h5=set_question(question_18)
      %b=q_response(@rating.rating_18)

= render layout: 'shared/rating_group', locals: {rating_title: 'Hitting', rating_class: 'hitting'} do
  %ul.list-group
    %li.list-group-item
      %h5=set_question(question_19)
      %b=q_response(@rating.rating_19)
    %li.list-group-item
      %h5=set_question(question_20)
      %b=q_response(@rating.rating_20)
    %li.list-group-item
      %h5=set_question(question_21)
      %b=q_response(@rating.rating_21)
    %li.list-group-item
      %h5=set_question(question_22)
      %b=q_response(@rating.rating_22)
    %li.list-group-item
      %h5=set_question(question_23)
      %b=q_response(@rating.rating_23)
    %li.list-group-item
      %h5=set_question(question_24)
      %b=q_response(@rating.rating_24)    
    %li.list-group-item
      %h5=set_question(question_25)
      %b=q_response(@rating.rating_25)
    %li.list-group-item
      %h5=set_question(question_26)
      %b=q_response(@rating.rating_26)
    %li.list-group-item
      %h5=set_question(question_27)
      %b=q_response(@rating.rating_27)

app/views/ratings/show_duplicates.html.haml
- content_for :panel_head do
  %h1 
    Duplicate Ratings
  = link_to "Remove All Duplicates", '/rating/duplicates/remove', :class => 'btn btn-default'

- if @duplicate_ratings.length > 0
  %table.table.table-striped.table-condensed.table-bordered
    %tr
      %th Id
      %th Player
      %th Player Id
      %th Rating
      %th Updated At
      %th Actions


    - @duplicate_ratings.each do |rating|
      %tr
        %td=rating.id
        %td
          -if rating.profile
            =rating.profile.name
        %td
          -if rating.profile
            =rating.profile_id
        %td
          =rating.total
        %td
          %span.small-text=rating.updated_at.strftime("%m/%d/%Y at %I:%M%p")
        %td= render partial: "shared/actions/delete", locals: { deleteItem: rating, deleteText: ''}
- else
  .well
    No Duplicate Ratings Found!